<a href="https://colab.research.google.com/github/Anuubhavvvv/Project-Python/blob/main/Diabetes_RF_Cls_10_11_30pm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df= pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [ ]:
df.shape

(768, 9)

In [ ]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
df.corr()

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.129459       0.141282      -0.081672   
Glucose                      0.129459  1.000000       0.152590       0.057328   
BloodPressure                0.141282  0.152590       1.000000       0.207371   
SkinThickness               -0.081672  0.057328       0.207371       1.000000   
Insulin                     -0.073535  0.331357       0.088933       0.436783   
BMI                          0.017683  0.221071       0.281805       0.392573   
DiabetesPedigreeFunction    -0.033523  0.137337       0.041265       0.183928   
Age                          0.544341  0.263514       0.239528      -0.113970   
Outcome                      0.221898  0.466581       0.065068       0.074752   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.073535  0.017683                 -0.033523   
Glucose                   0.331357  0.221071                  0.137337   
BloodPressure             0.088933  0.281805                  0.041265   
SkinThickness             0.436783  0.392573                  0.183928   
Insulin                   1.000000  0.197859                  0.185071   
BMI                       0.197859  1.000000                  0.140647   
DiabetesPedigreeFunction  0.185071  0.140647                  1.000000   
Age                      -0.042163  0.036242                  0.033561   
Outcome                   0.130548  0.292695                  0.173844   

                               Age   Outcome  
Pregnancies               0.544341  0.221898  
Glucose                   0.263514  0.466581  
BloodPressure             0.239528  0.065068  
SkinThickness            -0.113970  0.074752  
Insulin                  -0.042163  0.130548  
BMI                       0.036242  0.292695  
DiabetesPedigreeFunction  0.033561  0.173844  
Age                       1.000000  0.238356  
Outcome                   0.238356  1.000000

In [ ]:
# Glucose, BloodPressure, SkinThickness, Insulin and BMI

In [ ]:
glu0 = df[df['Glucose']==0].shape
bp0 = df[df['BloodPressure']==0].shape
st0 = df[df['SkinThickness']==0].shape
in0 = df[df['Insulin']==0].shape
bmi0 = df[df['BMI']==0].shape
print('Glu0',glu0)
print('BP0',bp0)
print('st0',st0)
print('in0',in0)
print('BMI0',bmi0)

Glu0 (5, 9)
BP0 (35, 9)
st0 (227, 9)
in0 (374, 9)
BMI0 (11, 9)


In [ ]:
glu_mean = df['Glucose'].mean()
bp_mean = df['BloodPressure'].mean()
st_mean = df['SkinThickness'].mean()
in_mean = df['Insulin'].mean()
bmi_mean = df['BMI'].mean()
print(glu_mean,bp_mean,st_mean,in_mean,bmi_mean)

120.89453125 69.10546875 20.536458333333332 79.79947916666667 31.992578124999977


In [ ]:
df['Glucose'].replace(0,glu_mean,inplace=True)
df['BloodPressure'].replace(0,bp_mean,inplace=True)
df['SkinThickness'].replace(0,st_mean,inplace=True)
df['Insulin'].replace(0,in_mean,inplace=True)
df['BMI'].replace(0,bmi_mean,inplace=True)

In [ ]:
glu0 = df[df['Glucose']==0].shape
bp0 = df[df['BloodPressure']==0].shape
st0 = df[df['SkinThickness']==0].shape
in0 = df[df['Insulin']==0].shape
bmi0 = df[df['BMI']==0].shape
print('Glu0',glu0)
print('BP0',bp0)
print('st0',st0)
print('in0',in0)
print('BMI0',bmi0)

Glu0 (0, 9)
BP0 (0, 9)
st0 (0, 9)
in0 (0, 9)
BMI0 (0, 9)


In [ ]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
print(x.shape)
print(y.shape)

(768, 8)
(768,)


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(576, 8)
(192, 8)
(576,)
(192,)


In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf1 = RandomForestClassifier(n_estimators=20) # criterion='gini'
rf1.fit(x_train,y_train)

RandomForestClassifier(n_estimators=20)

In [ ]:
print('Training accuracy',rf1.score(x_train,y_train))
print('Testing accuracy',rf1.score(x_test,y_test))

Training accuracy 0.9965277777777778
Testing accuracy 0.734375


In [ ]:
y_pred_rf1 = rf1.predict(x_test)
# y_pred_rf1

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score

In [ ]:
cm = confusion_matrix(y_test,y_pred_rf1)
print(cm)

[[107  15]
 [ 36  34]]


In [ ]:
print(accuracy_score(y_test,y_pred_rf1))

0.734375


In [ ]:
print(classification_report(y_test,y_pred_rf1))

              precision    recall  f1-score   support

           0       0.75      0.88      0.81       122
           1       0.69      0.49      0.57        70

    accuracy                           0.73       192
   macro avg       0.72      0.68      0.69       192
weighted avg       0.73      0.73      0.72       192



In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
# max_depth=[3,4,5,6,7,8,9]
# for i in max_depth:
scores = cross_val_score(RandomForestClassifier(),x,y)
print(scores)
print(f'{scores.mean()}')

[0.77922078 0.74025974 0.75324675 0.83006536 0.75816993]
0.772192513368984


### CV with max_depth

In [ ]:
max_depth=[3,4,5,6,7,8,9]
for i in max_depth:
    scores = cross_val_score(RandomForestClassifier(max_depth=i),x,y)
    print(f'At max_depth {i} the {scores.mean()}')

At max_depth 3 the 0.7565826330532213
At max_depth 4 the 0.7578643578643579
At max_depth 5 the 0.7695866225277989
At max_depth 6 the 0.7604872251931075
At max_depth 7 the 0.7631016042780749
At max_depth 8 the 0.7669807316866141
At max_depth 9 the 0.7604617604617605


### CV with criterion

In [ ]:
c=['gini','entropy']
for i in c:
    scores = cross_val_score(RandomForestClassifier(criterion=i),x,y)
    print(f'At criterion {i} the {scores.mean()}')

At criterion gini the 0.7500891265597147
At criterion entropy the 0.7617519735166794


### CV for min_samples_split

In [ ]:
mss =[3,4,5,6,7,8,9,11,13,24,25,100]
for i in mss:
    scores = cross_val_score(RandomForestClassifier(min_samples_split=i),x,y)
    print(f'At min_samples_split {i} the {scores.mean()}')

At min_samples_split 3 the 0.755258467023173
At min_samples_split 4 the 0.7539427892369069
At min_samples_split 5 the 0.7604872251931075
At min_samples_split 6 the 0.7683048977166624
At min_samples_split 7 the 0.7617774382480265
At min_samples_split 8 the 0.7578898225957049
At min_samples_split 9 the 0.7657074951192598
At min_samples_split 11 the 0.750097614803497
At min_samples_split 13 the 0.7591800356506239
At min_samples_split 24 the 0.7578728461081403
At min_samples_split 25 the 0.7553009082420847
At min_samples_split 100 the 0.7578728461081402


In [ ]:
bs =[True,False]
for i in bs:
    scores = cross_val_score(RandomForestClassifier(bootstrap=i),x,y)
    print(f'At bootstrap {i} the {scores.mean()}')

At bootstrap True the 0.7631100925218572
At bootstrap False the 0.748731007554537


In [ ]:
rf2 = RandomForestClassifier(criterion='entropy',max_depth=5,min_samples_split=6)
rf2.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=5, min_samples_split=6)

In [ ]:
print('Training accuracy',rf2.score(x_train,y_train))
print('Testing accuracy',rf2.score(x_test,y_test))

Training accuracy 0.8454861111111112
Testing accuracy 0.765625


In [ ]:
y_pred_rf2 = rf2.predict(x_test)
# y_pred_rf1

In [ ]:
cm = confusion_matrix(y_test,y_pred_rf2)
print(cm)

[[108  14]
 [ 31  39]]


In [ ]:
print(classification_report(y_test,y_pred_rf2))

              precision    recall  f1-score   support

           0       0.78      0.89      0.83       122
           1       0.74      0.56      0.63        70

    accuracy                           0.77       192
   macro avg       0.76      0.72      0.73       192
weighted avg       0.76      0.77      0.76       192



In [ ]:
name ="Rahul"
city='Nagpur'
print(name,'lives in',city)
print(f'{name} lives in {city}')
print('{} lives in {}'.format(name,city))

Rahul lives in Nagpur
Rahul lives in Nagpur
Rahul lives in Nagpur
