<a href="https://colab.research.google.com/github/Anuubhavvvv/Project-Python/blob/main/Energy_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [ ]:
df= pd.read_csv('/content/train_IxoE5JN.csv')


In [ ]:
# Replace infinite updated data with nan
df.replace([np.inf, -np.inf], np.nan, inplace=True)
# Drop rows with NaN
df.dropna(inplace=True)
print(df)

       row_id             datetime       energy
0           1  2008-03-01 00:00:00  1259.985563
1           2  2008-03-01 01:00:00  1095.541500
2           3  2008-03-01 02:00:00  1056.247500
3           4  2008-03-01 03:00:00  1034.742000
4           5  2008-03-01 04:00:00  1026.334500
...       ...                  ...          ...
94987   94988  2018-12-31 19:00:00  2528.446800
94988   94989  2018-12-31 20:00:00  2461.883600
94989   94990  2018-12-31 21:00:00  2365.994400
94990   94991  2018-12-31 22:00:00  2342.942800
94991   94992  2018-12-31 23:00:00  2180.217600

[93092 rows x 3 columns]


In [ ]:
df['datetime']=pd.to_datetime(df.datetime)


In [ ]:
x=['datetime']
y=['energy']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

ValueError: ignored

**logistic regression**


In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model=LogisticRegression()
model.fit(x_train,y_train)

TypeError: ignored

In [ ]:
print(model.score(x_test,y_test))
pred=model.predict(x_test)

0.84


In [ ]:
print(confusion_matrix(y_test,pred))

[[65  4]
 [12 19]]


In [ ]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.84      0.94      0.89        69
           1       0.83      0.61      0.70        31

    accuracy                           0.84       100
   macro avg       0.84      0.78      0.80       100
weighted avg       0.84      0.84      0.83       100



**Decision tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
print(dt.score(x_test,y_test))

0.86


In [ ]:
dt_pred=dt.predict(x_test)
dt_pred


array([0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0])

In [ ]:
print(confusion_matrix(y_test,dt_pred))


[[60  9]
 [ 5 26]]


In [ ]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.84      0.94      0.89        69
           1       0.83      0.61      0.70        31

    accuracy                           0.84       100
   macro avg       0.84      0.78      0.80       100
weighted avg       0.84      0.84      0.83       100



**RANDOM FOREST**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf= RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
print(rf.score(x_test,y_test))

0.95


In [ ]:
rf.pred=rf.predict(x_test)
rf.pred

array([0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0])

In [ ]:
print(confusion_matrix(y_test,rf.pred))

[[64  5]
 [ 0 31]]


In [ ]:
print(classification_report(y_test,rf.pred))

              precision    recall  f1-score   support

           0       1.00      0.93      0.96        69
           1       0.86      1.00      0.93        31

    accuracy                           0.95       100
   macro avg       0.93      0.96      0.94       100
weighted avg       0.96      0.95      0.95       100



**Scaling**

In [ ]:
from sklearn.model_selection import cross_val_score


**KNN**

In [ ]:
for i  in range(1,15):
  score=cross_val_score(KNeighborsClassifier(n_neighbors=i),x,y)
  print(f'At n {i},accuracy score is {score.mean()}')


At n 1,accuracy score is 0.665
At n 2,accuracy score is 0.73
At n 3,accuracy score is 0.7074999999999999
At n 4,accuracy score is 0.7275
At n 5,accuracy score is 0.7275
At n 6,accuracy score is 0.7475
At n 7,accuracy score is 0.74
At n 8,accuracy score is 0.755
At n 9,accuracy score is 0.755
At n 10,accuracy score is 0.755
At n 11,accuracy score is 0.75
At n 12,accuracy score is 0.7525
At n 13,accuracy score is 0.7525000000000001
At n 14,accuracy score is 0.7424999999999999


In [ ]:
cv_knn=KNeighborsClassifier(n_neighbors=10)

In [ ]:
cv_knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [ ]:
print(cv_knn.score(x_test,y_test))
cv_knn_pred=cv_knn.predict(x_test)
print(cv_knn_pred)

0.8
[0 1 0 1 0 1 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 0 1 0 0 0
 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0]


In [ ]:
print(confusion_matrix(y_test,cv_knn_pred))

[[64  5]
 [15 16]]


In [ ]:
print(classification_report(y_test,cv_knn_pred))

              precision    recall  f1-score   support

           0       0.81      0.93      0.86        69
           1       0.76      0.52      0.62        31

    accuracy                           0.80       100
   macro avg       0.79      0.72      0.74       100
weighted avg       0.80      0.80      0.79       100



**Log** **reg**

In [ ]:
for i  in range(1,15):
  score=cross_val_score(DecisionTreeClassifier(max_depth=i),x,y)
  print(f'At n {i},accuracy score is {score.mean()}')

At n 1,accuracy score is 0.7825000000000001
At n 2,accuracy score is 0.8875
At n 3,accuracy score is 0.8425
At n 4,accuracy score is 0.805
At n 5,accuracy score is 0.8099999999999999
At n 6,accuracy score is 0.8
At n 7,accuracy score is 0.805
At n 8,accuracy score is 0.8175000000000001
At n 9,accuracy score is 0.8125
At n 10,accuracy score is 0.8074999999999999
At n 11,accuracy score is 0.8074999999999999
At n 12,accuracy score is 0.8099999999999999
At n 13,accuracy score is 0.8125
At n 14,accuracy score is 0.8099999999999999


In [ ]:
criterion=['gini','entropy']

for i in criterion:
  score=cross_val_score(DecisionTreeClassifier(criterion=i),x,y)
  print(f'At {i},accuracy is {score.mean()}')
  print('At',i,",accuracy score is",score.mean())

At gini,accuracy is 0.7975
At gini ,accuracy score is 0.7975
At entropy,accuracy is 0.8099999999999999
At entropy ,accuracy score is 0.8099999999999999


In [ ]:

for i in range(3,15):
  score=cross_val_score(DecisionTreeClassifier(min_samples_split=i),x,y)
  print(f'At min_samples_split {i},accuracy score is {score.mean()}')

At min_samples_split 3,accuracy score is 0.7975
At min_samples_split 4,accuracy score is 0.8
At min_samples_split 5,accuracy score is 0.805
At min_samples_split 6,accuracy score is 0.7849999999999999
At min_samples_split 7,accuracy score is 0.7925000000000001
At min_samples_split 8,accuracy score is 0.7875
At min_samples_split 9,accuracy score is 0.7849999999999999
At min_samples_split 10,accuracy score is 0.7925
At min_samples_split 11,accuracy score is 0.8
At min_samples_split 12,accuracy score is 0.8025
At min_samples_split 13,accuracy score is 0.8025
At min_samples_split 14,accuracy score is 0.79


In [ ]:
cv_dt=DecisionTreeClassifier(criterion='gini',max_depth=2,min_samples_split=5)
cv_dt.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=2, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=5,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
cv_dt.score(x_test,y_test)

0.94

In [ ]:
cv_dt_pred=cv_dt.predict(x_test)

In [ ]:
print(cv_dt_pred)

[0 1 0 1 0 1 0 0 1 1 0 0 0 0 1 1 1 1 0 0 0 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0 1 0 1 0 0 1 0 1 0 1 1 0 0 0 1 0 0 0
 1 1 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0]


In [ ]:
confusion_matrix(y_test,cv_dt_pred)

array([[64,  5],
       [ 1, 30]])

In [ ]:
classification_report(y_test,cv_dt_pred)

'              precision    recall  f1-score   support\n\n           0       0.98      0.93      0.96        69\n           1       0.86      0.97      0.91        31\n\n    accuracy                           0.94       100\n   macro avg       0.92      0.95      0.93       100\nweighted avg       0.95      0.94      0.94       100\n'