<a href="https://colab.research.google.com/github/Anuubhavvvv/Project-Python/blob/main/Social_Network_Ads_Classification_Log_reg%2Cknn%2Cdecision_tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Social_Network_Ads ML Exercise

1) Read the dataset 'Social_Network_Ads.csv'<br>
2) Remove/handle null values<br>
3) Considering 'Age' and 'Estimated Salary' as input features and 'Purchased' as output feature, generate the following models after splitting the dataset into training and test dataset with test_size as 25%.<br>
a) Logistic Regression <br>
b) Decision Tree <br>
c) RandomForest <br>
d) KNN<br>
and predict the Purchased class label.<br>
4) Generate confusion matrix and classification report for each of these models.<br> 
5) Compute Accuracy score for each of these models.<br>
6) Scale the input features using feature Scaling and then repeat question 3, 4 and 5<br>

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df= pd.read_csv('/content/Social_Network_Ads.csv')

In [6]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [7]:
df ['Gender']=df['Gender'].apply({'Male':0 ,'Female':1}.get)

In [8]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       0   19            19000          0
1  15810944       0   35            20000          0
2  15668575       1   26            43000          0
3  15603246       1   27            57000          0
4  15804002       0   19            76000          0

In [9]:
x=['Gender',	'Age',	'EstimatedSalary']

y=['Purchased']

In [10]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [11]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
print(x.shape)
print(y.shape)

(400, 4)
(400,)


In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(300, 4)
(100, 4)
(300,)
(100,)


In [13]:
from sklearn.neighbors import  KNeighborsRegressor
from sklearn.neighbors import KNeighborsClassifier

In [14]:
k1=KNeighborsClassifier(n_neighbors=10)

In [15]:
k1.fit(x_train,y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [16]:
print('Training Accuracy',k1.score(x_train,y_train))
print('Testing Accuracy',k1.score(x_test,y_test))

Training Accuracy 0.7733333333333333
Testing Accuracy 0.8


In [17]:
ypre =k1.predict(x_test)
print(ypre)

[0 1 0 1 0 1 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 0 1 0 0 0
 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0]


In [18]:
from sklearn.metrics import confusion_matrix , classification_report

In [19]:
cr= classification_report(y_test,ypre)
print(cr)

              precision    recall  f1-score   support

           0       0.81      0.93      0.86        69
           1       0.76      0.52      0.62        31

    accuracy                           0.80       100
   macro avg       0.79      0.72      0.74       100
weighted avg       0.80      0.80      0.79       100



In [20]:
c= confusion_matrix(ypre,y_test)

In [21]:
print(c)

[[64 15]
 [ 5 16]]


In [22]:
from sklearn.preprocessing import StandardScaler

In [24]:
sc= StandardScaler()

**logistic regression**


In [25]:
from sklearn.linear_model import LogisticRegression

In [27]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [33]:
print(model.score(x_test,y_test))
pred=model.predict(x_test)

0.84


In [34]:
print(confusion_matrix(y_test,pred))

[[65  4]
 [12 19]]


In [35]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.84      0.94      0.89        69
           1       0.83      0.61      0.70        31

    accuracy                           0.84       100
   macro avg       0.84      0.78      0.80       100
weighted avg       0.84      0.84      0.83       100



**Decision tree**

In [37]:
from sklearn.tree import DecisionTreeClassifier

In [40]:
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [43]:
print(dt.score(x_test,y_test))

0.86


In [46]:
dt_pred=dt.predict(x_test)
dt_pred


array([0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0])

In [49]:
print(confusion_matrix(y_test,dt_pred))


[[60  9]
 [ 5 26]]


In [50]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.84      0.94      0.89        69
           1       0.83      0.61      0.70        31

    accuracy                           0.84       100
   macro avg       0.84      0.78      0.80       100
weighted avg       0.84      0.84      0.83       100



**RANDOM FOREST**

In [51]:
from sklearn.ensemble import RandomForestClassifier
rf= RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [57]:
print(rf.score(x_test,y_test))

0.95


In [59]:
rf.pred=rf.predict(x_test)
rf.pred

array([0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0])

In [61]:
print(confusion_matrix(y_test,rf.pred))

[[64  5]
 [ 0 31]]


In [62]:
print(classification_report(y_test,rf.pred))

              precision    recall  f1-score   support

           0       1.00      0.93      0.96        69
           1       0.86      1.00      0.93        31

    accuracy                           0.95       100
   macro avg       0.93      0.96      0.94       100
weighted avg       0.96      0.95      0.95       100



**Scaling**

In [64]:
from sklearn.model_selection import cross_val_score


**KNN**

In [74]:
for i  in range(1,15):
  score=cross_val_score(KNeighborsClassifier(n_neighbors=i),x,y)
  print(f'At n {i},accuracy score is {score.mean()}')


At n 1,accuracy score is 0.665
At n 2,accuracy score is 0.73
At n 3,accuracy score is 0.7074999999999999
At n 4,accuracy score is 0.7275
At n 5,accuracy score is 0.7275
At n 6,accuracy score is 0.7475
At n 7,accuracy score is 0.74
At n 8,accuracy score is 0.755
At n 9,accuracy score is 0.755
At n 10,accuracy score is 0.755
At n 11,accuracy score is 0.75
At n 12,accuracy score is 0.7525
At n 13,accuracy score is 0.7525000000000001
At n 14,accuracy score is 0.7424999999999999


In [75]:
cv_knn=KNeighborsClassifier(n_neighbors=10)

In [76]:
cv_knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [83]:
print(cv_knn.score(x_test,y_test))
cv_knn_pred=cv_knn.predict(x_test)
print(cv_knn_pred)

0.8
[0 1 0 1 0 1 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 0 1 0 0 0
 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0]


In [84]:
print(confusion_matrix(y_test,cv_knn_pred))

[[64  5]
 [15 16]]


In [85]:
print(classification_report(y_test,cv_knn_pred))

              precision    recall  f1-score   support

           0       0.81      0.93      0.86        69
           1       0.76      0.52      0.62        31

    accuracy                           0.80       100
   macro avg       0.79      0.72      0.74       100
weighted avg       0.80      0.80      0.79       100



**Log** **reg**

In [88]:
for i  in range(1,15):
  score=cross_val_score(DecisionTreeClassifier(max_depth=i),x,y)
  print(f'At n {i},accuracy score is {score.mean()}')

At n 1,accuracy score is 0.7825000000000001
At n 2,accuracy score is 0.8875
At n 3,accuracy score is 0.8425
At n 4,accuracy score is 0.805
At n 5,accuracy score is 0.8099999999999999
At n 6,accuracy score is 0.8
At n 7,accuracy score is 0.805
At n 8,accuracy score is 0.8175000000000001
At n 9,accuracy score is 0.8125
At n 10,accuracy score is 0.8074999999999999
At n 11,accuracy score is 0.8074999999999999
At n 12,accuracy score is 0.8099999999999999
At n 13,accuracy score is 0.8125
At n 14,accuracy score is 0.8099999999999999


In [93]:
criterion=['gini','entropy']

for i in criterion:
  score=cross_val_score(DecisionTreeClassifier(criterion=i),x,y)
  print(f'At {i},accuracy is {score.mean()}')
  print('At',i,",accuracy score is",score.mean())

At gini,accuracy is 0.7975
At gini ,accuracy score is 0.7975
At entropy,accuracy is 0.8099999999999999
At entropy ,accuracy score is 0.8099999999999999


In [95]:

for i in range(3,15):
  score=cross_val_score(DecisionTreeClassifier(min_samples_split=i),x,y)
  print(f'At min_samples_split {i},accuracy score is {score.mean()}')

At min_samples_split 3,accuracy score is 0.7975
At min_samples_split 4,accuracy score is 0.8
At min_samples_split 5,accuracy score is 0.805
At min_samples_split 6,accuracy score is 0.7849999999999999
At min_samples_split 7,accuracy score is 0.7925000000000001
At min_samples_split 8,accuracy score is 0.7875
At min_samples_split 9,accuracy score is 0.7849999999999999
At min_samples_split 10,accuracy score is 0.7925
At min_samples_split 11,accuracy score is 0.8
At min_samples_split 12,accuracy score is 0.8025
At min_samples_split 13,accuracy score is 0.8025
At min_samples_split 14,accuracy score is 0.79


In [97]:
cv_dt=DecisionTreeClassifier(criterion='gini',max_depth=2,min_samples_split=5)
cv_dt.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=2, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=5,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [99]:
cv_dt.score(x_test,y_test)

0.94

In [101]:
cv_dt_pred=cv_dt.predict(x_test)

In [102]:
print(cv_dt_pred)

[0 1 0 1 0 1 0 0 1 1 0 0 0 0 1 1 1 1 0 0 0 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0 1 0 1 0 0 1 0 1 0 1 1 0 0 0 1 0 0 0
 1 1 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0]


In [103]:
confusion_matrix(y_test,cv_dt_pred)

array([[64,  5],
       [ 1, 30]])

In [104]:
classification_report(y_test,cv_dt_pred)

'              precision    recall  f1-score   support\n\n           0       0.98      0.93      0.96        69\n           1       0.86      0.97      0.91        31\n\n    accuracy                           0.94       100\n   macro avg       0.92      0.95      0.93       100\nweighted avg       0.95      0.94      0.94       100\n'